name: Alerting
on:
  push:
  schedule:
    - cron: '1 */1 * * *'
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: check
        run: |
          cd ./cmd/alert
          go build
          ./alert --htmlbody ./body.html

      - name: Send notification email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: EthStorage Alert!
          to: molaokp@gmail.com
          from: ${{ secrets.SMTP_USERNAME }}
          body: ./cmd/alert/body.html